str_1 = 'разработка'
str_2 = 'сокет'
str_3 = 'декоратор'
print(type(str_1))
print(str_1)
print(type(str_2))
print(str_2)
print(type(str_3))
print(str_3)
str_1 = str_1.encode('utf-8')
str_2 = str_2.encode('utf-8')
str_3 = str_3.encode('utf-8')
print(type(str_1))
print(str_1)
print(type(str_2))
print(str_2)
print(type(str_3))
print(str_3)
str_1 = str_1.decode('utf-8')
str_2 = str_2.decode('utf-8')
str_3 = str_3.decode('utf-8')
print(type(str_1))
print(str_1)
print(type(str_2))
print(str_2)
print(type(str_3))
print(str_3)
